// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlSfZkn_IxjpP-6a2u5awfLNejxd22LfY',
    appId: '1:75198792000:web:523e16009f70016e47baa5',
    messagingSenderId: '75198792000',
    projectId: 'tik-tok-clone-seanwho',
    authDomain: 'tik-tok-clone-seanwho.firebaseapp.com',
    storageBucket: 'tik-tok-clone-seanwho.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvp-CJstWqioEsRFo_pQMlReHz-yH5Xj0',
    appId: '1:75198792000:android:2e48fd222b53e23147baa5',
    messagingSenderId: '75198792000',
    projectId: 'tik-tok-clone-seanwho',
    storageBucket: 'tik-tok-clone-seanwho.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpSYfWhNxYFpa8l6zveOvZKyBX6IAQ0_8',
    appId: '1:75198792000:ios:ee55bb061bed1a7847baa5',
    messagingSenderId: '75198792000',
    projectId: 'tik-tok-clone-seanwho',
    storageBucket: 'tik-tok-clone-seanwho.appspot.com',
    iosBundleId: 'com.allan0215.tiktokClone',
  );

}